tasks:
  - init: mysql -u root -e "create database agent_banking" && cp .env.example .env && composer install && npm i && php artisan key:generate
    command: php artisan migrate --seed && php artisan serve
image:
  file: .gitpod.Dockerfile
